version: "3.9"
name: gnosql
services:
    gnosql:
        container_name: "gnosql"
        image: gnosql
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            # <<local host port >>:<<container port>>
            - 5454:5454
        volumes:
            - .:/app
        environment:
            PORT: 5454
            GIN_MODE: release
