version: "3.9"
name: gnosql
services:
    gnosql:
        container_name: "gnosql"
        image: nanda23311/gnosql:latest
        ports:
            - 5454:5454
        volumes:
            - gnosqldb-data:/root/gnosql/db/
        environment:
            PORT: 5454
volumes:
    gnosqldb-data:
        name: gnosqldb-data
