version: "3.9"
name: gnosql
services:
    gnosql:
        container_name: "gnosql"
        image: nanda03dev/gnosql:latest
        ports:
            # <<local host port >>:<<container port>>
            - 5454:5454
            - 5455:5455
        volumes:
            - gnosqldb-data:/root/gnosql/db/
        environment:
            GIN_PORT: 5454
            GRPC_PORT: 5455
            GIN_MODE: debug
volumes:
    gnosqldb-data:
        name: gnosqldb-data
