version: "3.9"
name: gnosql-local
services:
    gnosql:
        container_name: "gnosql-local"
        build:
            context: .
            dockerfile: Dockerfile.local
        ports:
            # <<local host port >>:<<container port>>
            - 5454:5454
            - 5455:5455
        volumes:
            - gnosqldb-data-local:/root/gnosql/db/
        environment:
            GIN_PORT: 5454
            GRPC_PORT: 5455
            GIN_MODE: debug
volumes:
    gnosqldb-data-local:
        name: gnosqldb-data-local
