version: "3.9"
name: gnosql
services:
    gnosql:
        container_name: "gnosql"
        image: gnosql
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            # <<local host port >>:<<container port>>
            - 8080:8080
        environment:
            PORT: 8080
