version: "3.9"
name: gnosql
services:
    gnosql:
        container_name: "gnosql"
        image: gnosql
        build:
            context: .
            dockerfile: Dockerfile.local
        ports:
            # <<local host port >>:<<container port>>
            - 5454:3000
        volumes:
            - .:/app
        environment:
            PORT: 3000
            GIN_MODE: debug
