version: "3.9"
name: gnosql
services:
    gnosql:
        container_name: "gnosql"
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            # <<local host port >>:<<container port>>
            - 5454:5454
            - 5455:5455
        volumes:
            - gnosqldb-data:/root/gnosql/db/
        environment:
            GIN_PORT: 5454
            GRPC_PORT: 5455
            GIN_MODE: release
volumes:
    gnosqldb-data:
        name: gnosqldb-data
